apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: grand-hare-java-quarkus 
  janus-idp.io/tekton: grand-hare-java-quarkus
  backstage.io/kubernetes-id: grand-hare-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-integ 
  app.kubernetes.io/part-of: grand-hare-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  